# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-09-28 06:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=30)),
                ('last_name', models.CharField(max_length=30)),
                ('email', models.EmailField(max_length=254)),
                ('about', models.TextField(max_length=30)),
                ('skills', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('description', models.CharField(max_length=50)),
                ('github_acct', models.CharField(max_length=30)),
                ('proj_image', models.ImageField(upload_to='portfolio/')),
                ('pub_date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
